liip_imagine:
    resolvers:
        default:
            web_path:
                cache_prefix: media

    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    cache: default
    data_loader: default
    default_image: null

    # define your filter sets under this option
    filter_sets:

        cache: ~

        # Filtre d'image pour les avatar des utilisateurs
        user_avatar:

            # adjust the image quality to 75%
            quality: 90

            # list of transformations to apply (the "filters")
            filters:

                # create a thumbnail: set size to 120x90 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail: { size: [100, 120], mode: outbound }

        # Filtre d'image pour les avatar de CV
        cv_avatar:

            # adjust the image quality to 75%
            quality: 90

            # list of transformations to apply (the "filters")
            filters:

                # create a thumbnail: set size to 120x90 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail: { size: [200, 250], mode: outbound }

        # Filtre d'image pour les avatar de themes
        theme_avatar:

            # adjust the image quality to 75%
            quality: 90

            # list of transformations to apply (the "filters")
            filters:

                # create a thumbnail: set size to 120x90 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail: { size: [298, 421], mode: outbound }
