security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt

    providers:
        in_database:
            id: App\Provider\UserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:    ^/
            anonymous:  ~
            provider: in_database
            form_login:
                login_path: connexion
                check_path: connexion
                username_parameter: username
                password_parameter: password
            logout:
                path:   deconnexion
                target: home

    access_control:
         - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/(connexion|inscription), roles: IS_AUTHENTICATED_ANONYMOUSLY }
