security:
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    encoders:
        App\Entity\User:
            algorithm: bcrypt

    providers:
        in_database:
            id: App\Provider\UserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:    ^/
            anonymous:  ~
            provider: in_database
            form_login:
                login_path: connexion
                check_path: connexion
                username_parameter: username
                password_parameter: password
                default_target_path: dashboard
            logout:
                path:   deconnexion
                target: home

    access_control:
        - { path: ^/(connexion|inscription), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
