sonata_admin:
    title: 'CVThèque'
    search: false
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
        groups:
            app.admin.group.user:
                label: Utilisateurs
                icon: '<i class="fa fa-users"></i>'
                items:
                    - app.admin.user
            app.admin.group.cv:
                label: CV
                icon: '<i class="fa fa-file-text-o"></i>'
                items:
                    - app.admin.cv

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
