home:
    path: /
    controller: App\Controller\HomeController::index

connexion:
    path: /connexion
    controller: App\Controller\ConnexionController::index

inscription:
    path: /inscription
    controller: App\Controller\InscriptionController::index

confirmation_inscription:
    path: /confirmation-inscription/{token}
    controller: App\Controller\InscriptionController::confirmationInscription

deconnexion:
    path: /deconnexion

dashboard:
    path: /dashboard
    controller: App\Controller\DashboardController::index

profil:
    path: /profil
    controller: App\Controller\ProfilController::index

cv_ajouter:
    path: /cv/ajouter
    controller: App\Controller\CV\AjouterController::index

cv_modifier:
    path: /cv/modifier/{id}
    controller: App\Controller\CV\ModifierController::index
    requirements:
        id: \d+
