home:
    path: /
    controller: App\Controller\HomeController::index

connexion:
    path: /connexion
    controller: App\Controller\ConnexionController::index

inscription:
    path: /inscription
    controller: App\Controller\InscriptionController::index

confirmation_inscription:
    path: /confirmation-inscription/{token}
    controller: App\Controller\InscriptionController::confirmationInscription

deconnexion:
    path: /deconnexion

dashboard:
    path: /dashboard
    controller: App\Controller\DashboardController::index

profil:
    path: /profil
    controller: App\Controller\ProfilController::index

cv_ajouter:
    path: /cv/ajouter
    controller: App\Controller\Cv\AjouterController::index

cv_modifier:
    path: /cv/modifier/{id}
    controller: App\Controller\Cv\ModifierController::index
    requirements:
        id: \d+

cv_partage:
    path: /cv/{cv}
    controller: App\Controller\Cv\PartageController::index
    requirements:
        id: \d+

theme_list_json:
    path: /themes/{cv}
    controller: App\Controller\ThemeController::list
    requirements:
        cv: \d+

change_theme:
    path: /themes/set
    controller: App\Controller\ThemeController::change

