home:
    path: /
    controller: App\Controller\HomeController::index

connexion:
    path: /connexion
    controller: App\Controller\ConnexionController::index

inscription:
    path: /inscription
    controller: App\Controller\InscriptionController::index
