version: '3.0'
services:
    database:
        image: mysql:5.7
        volumes:
            - ./dockerfiles/database/data:/var/lib/mysql
            - ./dockerfiles/database/import:/import
        environment:
            - "MYSQL_ROOT_PASSWORD=${BDD_MYSQL_ROOT_PASSWORD}"
            - "MYSQL_USER=${BDD_MYSQL_USER}"
            - "MYSQL_PASSWORD=${BDD_MYSQL_PASSWORD}"
            - "MYSQL_DATABASE=${BDD_MYSQL_DATABASE}"

    php:
        build: ./dockerfiles/php
        volumes:
            - ${SOURCE_ROOT_FOLDER}:/var/www
        depends_on:
            - database
        environment:
            - PRODUCTION=false

    httpd:
        build: ./dockerfiles/httpd
        volumes:
            - ${SOURCE_ROOT_FOLDER}:/var/www
        depends_on:
            - php
